name: monitoring_penyiraman
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_database: ^10.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
